### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Tosible** [MikeKamau/tolk#1] opened 2016-01-23 13:57 UTC
Your script works, but if you capture the requests it sends using Wireshark, it says, "Connection: close" instead of "Connection: keep-alive". 
The problem is urllib2, they override the Connection header.

Any fix for this? I looked online to try and improve this, but nothing.

**Comment by MikeKamau** [comment] 2016-01-25 05:41
Hi,
Sorry for the late response, I've been kind of swamped lately. Thanks for the heads up, I really appreciate it.Will look into it and update the repo once I get a solution.:-)

```
On Saturday, January 23, 2016 4:57 PM, Pr0xy671 <notifications@github.com> wrote:
```

 Your script works, but if you capture the requests it sends using Wireshark, it says, "Connection: close" instead of "Connection: keep-alive" 
The problem is urllib2, they override the Connection headerAny fix for this? I looked online to try and improve this, but nothing —

**Comment by Tosible** [comment] 2016-01-25 05:54
This is not a huge problem, and it doesn't affect performance. But it makes
Tolk easier to detect and mitigate because it has a keep-alive header, yet
it's connection is close.

I found an alternative, the module "requests". I'm busy right now but when
I have the time, I'll fork Tolk, implement the requests module and do a
pull requests.

**Comment by Tosible** [comment] 2016-02-09 19:16
Hey is it possible to randomize the header order?

**Comment by MikeKamau** [comment] 2016-02-18 06:29
Hi, 
Sorry for the silence, its been a crazy for the last two weeks. I believe its possible to randomize the headers, and will look into it this weekend. 

```
On Tuesday, February 9, 2016 10:16 PM, Pr0xy671 <notifications@github.com> wrote:
```

 Hey is it possible to randomize the header order?—

**Comment by Tosible** [comment] 2016-02-20 04:31
Edit: Forget what I said, is it possible to disconnect from Tor when a ConnectionError is raised?

**Comment by MikeKamau** [comment] 2016-02-21 07:40
Hi, I've looked over the code and the header order is already randomized. As for the ConnectionError matter, I wanted to get clarification, do you suggest tolk disconnects from tor and connects directly or diconnects altogether when a ConnectionError is raised.

**Comment by MikeKamau** [comment] 2016-02-25 13:31
Ok, will work on that and update the repo once its finalized.

```
On Saturday, February 20, 2016 7:31 AM, Pr0xy671 <notifications@github.com> wrote:
```

 Can you also implement this: 
https://github.com/Zalvie/cloudflare-scrape-out-pyv8/blob/master/cfscrape.pyIt's to bypass Cloudflare's JavaScript checks without the need of PyV8 engine.—

**Comment by Tosible** [comment] 2016-02-25 19:49
All done :) 
I submitted a pull requests :+1: 
Right now, I'm going to try and implement Captcha solving. I might need help.

**Closed as completed** 2017-04-09 08:20 UTC
